# Generated by Django 4.2.11 on 2025-02-27 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNum', models.CharField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A3'), (4, 'A4'), (5, 'A5'), (6, 'A6'), (7, 'A7'), (8, 'B1'), (9, 'B2'), (10, 'B3'), (11, 'B4'), (12, 'B5'), (13, 'B6'), (14, 'B7'), (15, 'C1'), (16, 'C2'), (17, 'C3'), (18, 'C4'), (19, 'C5'), (20, 'C6'), (21, 'C7'), (22, 'D1'), (23, 'D2'), (24, 'D3'), (25, 'D4'), (26, 'D5'), (27, 'D6'), (28, 'D7'), (29, 'E1'), (30, 'E2'), (31, 'E3'), (32, 'E4'), (33, 'E5'), (34, 'E6'), (35, 'E7'), (36, 'F1'), (37, 'F2'), (38, 'F3'), (39, 'F4'), (40, 'F5'), (41, 'F6'), (42, 'F7')], max_length=50, unique=True)),
                ('status', models.CharField(choices=[('R', 'Reserved'), ('A', 'Available')], max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.movie')),
            ],
            options={
                'unique_together': {('movie', 'seatNum')},
            },
        ),
    ]
