# Generated by Django 4.2.11 on 2025-02-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seatNum',
            field=models.CharField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A3'), (4, 'A4'), (5, 'A5'), (6, 'B1'), (7, 'B2'), (8, 'B3'), (9, 'B4'), (10, 'B5'), (11, 'C1'), (12, 'C2'), (13, 'C3'), (14, 'C4'), (15, 'C5'), (16, 'D1'), (17, 'D2'), (18, 'D3'), (19, 'D4'), (20, 'D5'), (21, 'E1'), (22, 'E2'), (23, 'E3'), (24, 'E4'), (25, 'E5'), (26, 'F1'), (27, 'F2'), (28, 'F3'), (29, 'F4'), (30, 'F5')], max_length=50, unique=True),
        ),
    ]
