# Generated by Django 4.2.11 on 2025-02-28 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_booking_date_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 28, 23, 11, 53, 164634, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'), ('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5')], max_length=10, unique=True, unique_for_date=models.DateField(default=datetime.datetime(2025, 2, 28, 23, 11, 53, 164634, tzinfo=datetime.timezone.utc))),
        ),
    ]
