# Generated by Django 4.2.11 on 2025-03-01 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_booking_date_alter_booking_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 3, 18, 52, 283270, tzinfo=datetime.timezone.utc)),
        ),
    ]
