# Generated by Django 4.2.11 on 2025-03-01 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_booking_booking_one_seat_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 9, 7, 13, 377105, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('R', 'Reserved'), ('A', 'Available')], default='A', max_length=50),
        ),
    ]
