# Generated by Django 4.2.11 on 2025-03-01 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_alter_booking_date_alter_seat_seatnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_movie',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 19, 12, 27, 893272, tzinfo=datetime.timezone.utc)),
        ),
    ]
