# Generated by Django 4.2.11 on 2025-03-01 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_remove_seat_seat_movie_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 19, 13, 8, 619713, tzinfo=datetime.timezone.utc)),
        ),
    ]
