# Generated by Django 4.2.11 on 2025-03-02 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_alter_booking_date_alter_booking_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 7, 2, 59, 509032, tzinfo=datetime.timezone.utc)),
        ),
    ]
