# Generated by Django 4.2.11 on 2025-03-02 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_alter_booking_date_alter_booking_seat_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='one_seat_per_person',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 7, 26, 51, 291778, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('movie', 'seat', 'date'), name='one_seat_per_person_per_day'),
        ),
    ]
