# Generated by Django 4.2.11 on 2025-03-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_remove_booking_one_seat_per_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.movie'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
